language: node_js
node_js:
  - "4.2.2"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 1 # give server time to start
  - npm install -g bower
  - bower install

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers PhantomJS
